apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: '*.example.com' # your domain
  dnsNames:
  - 'example.com' # your domain
  - '*.example.com' # your domain
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
